### ISSUE TITLE
[Documentation]Show how to install and use the project with Composer

### ISSUE THREAD

**Issue by greg0ire** [FriendsOfPHP/Sismo#120]
There are a few awesome features that lack documentation : 
1. How to install sismo <del>globally</del> with Composer
2. How to use the document root in `$HOME/.composer/sismo/sismo/web` with a web server configuration.
3. How set the `$app['debug']` setting through the config (is it even possible ? I had to edit a file to set it to true).

If you are interested, I can make a P.R.

**Comment by naitsirch** [comment]
I think this issue can be closed, or not?

**Comment by greg0ire** [comment]
Feel free to
